### ISSUE TITLE
getOtherRepInfo and sr.roi.bed file

### ISSUE THREAD

**Issue by creggian** [qiaseq/qiaseq-smcounter-v2#13]
Hi,

I am using smcounter2 (commit `a52dfe2`) in my bioinformatic pipeline and I downloaded the background and annotation files as indicated in the Dockerfile. I get the following error in the middle of the analysis

```
Traceback (most recent call last):
  File "/u/creggian/programmi/qiaseq-smcounter-v2-dev/run.py", line 177, in <module>
    main(args)
  File "/u/creggian/programmi/qiaseq-smcounter-v2-dev/run.py", line 92, in main
    srRegion = utils.getOtherRepInfo(bedTarget, args.srBed, args.isRna, args.hpLen)
  File "/sulb4/creggian/programmi/qiaseq-smcounter-v2-dev/utils.py", line 177, in getOtherRepInfo
    repType, totalLen, unitLen, repLen, repBase = repInfo.strip().split("|")
ValueError: too many values to unpack
```

Giving a look at the `sr.roi.bed` generated here there the first lines.

```
chr10	43615213	43615245	trf|31|2|30|84|9|79|19|59|16|4|1.55|ACCCAGCCAGCCCCGGCCACCCACACCCTG
chr11	5247111	5247146	trf|16|2.2|16|94|0|61|40|5|14|40|1.69|ATTTATATGCAGAAAT
chr2	48982755	48982790	trf|9|3.9|9|84|0|52|22|34|31|11|1.9|GCTGCAGCA
```

The error is that the last field has more than 5 subfields separated by `|`, hence the error.

Do you have any suggestion to fix this error?

Thanks
Claudio

**Comment by creggian** [comment]
Sorry, I inverted the simplerepeat file with the SR file when I gave them as parameter.

Now it works.
