### ISSUE TITLE
region format for pysam pileup (vc.py line 298)

### ISSUE THREAD

**Issue by knishimiya** [qiaseq/qiaseq-smcounter-v2#16]
Dear developers,

I tried to use smCounter for my bioinformatics pipeline.
But following error happen and the program exit in the middle.

    Traceback (most recent call last):
      File "../qiaseq-smcounter-v2/run.py", line 177, in <module>
        main(args)
      File "../qiaseq-smcounter-v2/run.py", line 128, in main
        for interval_result in pool.map(func,locList):
      File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
        return self.map_async(func, iterable, chunksize).get()
      File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
        raise self._value
    UnboundLocalError: local variable 'pos' referenced before assignment

I looked into the error and found out what can be considered a cause.

https://github.com/qiaseq/qiaseq-smcounter-v2/blob/18f05cf301a26f9fb2a26e7e1f880f0b8847bde1/vc.py#L295

You write region with the following format
\<chromosome\>:\<start\>:\<end\>

but I think that the following format is correct
\<chromosome\>:\<start\>-\<end\>

Difference between two formats is the delimiter between start and end.

This error seems to be caused by modification of pysam/libchtslib.pyx.

https://github.com/pysam-developers/pysam/blob/e69a124140da5d10f1da7dd8095bea8dc46bff1a/pysam/libchtslib.pyx#L667

Please confirm it.

Best regards,

koh

**Comment by rpadmanabhan** [comment]
Hi koh,
The pysam version we used in smcounter is really old (0.9.0) , so maybe the api for the pileup region specification is different now. What version of pysam are you using ? 
We recommend using our Docker image rpadmanabhan9/qiaseq-dna:pipeline if you our running our qiaseq-dna fastq to vcf pipeline.
If you are just running smcounter-v2 , you can use this smaller one : rpadmanabhan9/qiaseq-dna:smcounter-v2

**Comment by knishimiya** [comment]
Hi @rpadmanabhan ,
I'm using pysam version 0.15.2.

>  If you are just running smcounter-v2 , you can use this smaller one : rpadmanabhan9/qiaseq-dna:smcounter-v2

I will use that one.
Thanks!

**Comment by Lewis-Gallagher** [comment]
Hi,

I'm getting this error when running smcounter-v2 via your docker image rpadmanabhan9/qiaseq-dna:smcounter-v2.  I'm trying to take a consensus bam file generated from an fgbio pipeline I have adapted and variant call with smCounter2.  Here's the command I'm running.  

```
python /srv/qgen/code/qiaseq-smcounter-v2/run.py \
    --runPath /mnt/qiaseq-run/ \
    --bamFile /mnt/qiaseq-run/1801430-1033-T.consensus.filtered.aln.merged.bam \
    --bedTarget /srv/qgen/test_smcounter-v2/high.confidence.variants.bed \
    --outPrefix 20190304- \
    --bamType consensus \
    --nCPU 4 \ 
    --minBQ 25 \
     --minMQ 50 \
    --hpLen 8 \ 
    --mismatchThr 6.0 \
    --primerDist 2 \ 
    --mtThreshold 0.8 \
    --rpb 7.6 \
    --primerSide 1 \ 
    --minAltUMI 3 \ 
    --maxAltAllele 2 \ 
    --refGenome /srv/qgen/data/genome/ucsc.hg19.fa \
    --srBed /srv/qgen/data/annotation/SR_LC_SL.full.bed \
    --repBed /srv/qgen/data/annotation/simpleRepeat.full.bed                                                                    
```

```
root@ac63966d5ace:/mnt/qiaseq-run# source scripts/smcounter2.sh 
started 2019-03-04 15:30:33.812261
('repBed', '/srv/qgen/data/annotation/simpleRepeat.full.bed')
('bamFile', '/mnt/qiaseq-run/1801430-1033-T.consensus.filtered.aln.merged.bam')
('rpb', 7.6)
('bkgErrorDistSimulation', '/srv/qgen/data/annotation/bkg.error.v2.RData')
('mismatchThr', 6.0)
('hpLen', 8)
('inputVCF', 'none')
('srBed', '/srv/qgen/data/annotation/SR_LC_SL.full.bed')
('bamType', 'consensus')
('refGenome', '/srv/qgen/data/genome/ucsc.hg19.fa')
('nCPU', 4)
('maxAltAllele', 2)
('primerDist', 2)
('bedTarget', '/srv/qgen/test_smcounter-v2/high.confidence.variants.bed')
('primerSide', 1)
('mtThreshold', 0.8)
('runPath', '/mnt/qiaseq-run/')
('primerTag', 'pr')
('outPrefix', '20190304-')
('ds', 10000)
('minBQ', 25)
('tagSeparator', '-')
('mqTag', 'MQ')
('umiTag', 'Mi')
('isRna', False)
('minMQ', 50)
('minAltUMI', 3)
rpb = 7.6, given by user
runtime	interval
Traceback (most recent call last):
  File "/srv/qgen/code/qiaseq-smcounter-v2/run.py", line 181, in <module>
    main(args)
  File "/srv/qgen/code/qiaseq-smcounter-v2/run.py", line 132, in main
    for interval_result in pool.map(func,locList):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
UnboundLocalError: local variable 'pos' referenced before assignment
```

Cheers

Lewis

**Comment by hclifford** [comment]
Hi @Lewis-Gallagher 

Is your bam file indexed?
pysam won't build the pileups without a .bai

Best,
Harry
